### PR TITLE
Revert allocate_memory export, as it breaks builds

### PR DESCRIPTION
**Pull request by Jannis**
See https://github.com/graphprotocol/graph-cli/pull/160#issuecomment-435347390.

### CODE REVIEW

**Comment by Jannis** [comment]
I'm taking the liberty to merge this without a review to unblock other tasks. Let's review why this wasn't working next week @leodasvacas!

**Comment by leodasvacas** [comment]
Reverting this on both the here and in the cli was a bit overkill, reverting only one of them would probably have been sufficient. I think this approach can be salvaged, I'll take a look.

**Comment by Jannis** [comment]
CLI only reverts the example subgraph to exporting `allocate_memory` again, otherwise it wouldn't compile. `global/global.ts` is still passed in as a lib there.

**Comment by leodasvacas** [comment]
@Jannis ah cool, thanks for clarifying.

**Pull request merged**
