### PR TITLE
index: add support abi encode/decode

### PR DESCRIPTION
**Pull request by otaviopace**
Related issue: https://github.com/graphprotocol/graph-node/pull/2348
Related pull request: https://github.com/graphprotocol/graph-node/pull/2348

I think this Pull Request should have tests as well, how should I proceed with it?

### CODE REVIEW

**Comment by leoyvens** [comment]
These should go in the `ethereum` namespace, in `chains/ethereum.ts`

**Comment by otaviopace** [comment]
@leoyvens , should it the two functions be exported directly on `ethereum` namespace, or should I keep the `abi` namespace inside of it?

`ethereum.{decode, encode}` vs `ethereum.abi.{decode, encode}`

**Comment by leoyvens** [comment]
@otaviopace they can be directly in the namespace, no need to nest it.

**Comment by otaviopace** [comment]
@leoyvens this and [`graph-node`](https://github.com/graphprotocol/graph-node/pull/2348) are finished, I'm looking to see how I can contribute to the `docs`

**Comment by otaviopace** [comment]
@leoyvens I've removed the lock file, sorry!

**Review by leoyvens — APPROVED** [review]

**Comment by leoyvens** [comment]
You can merge and have the graph-node PR point to graph-ts master

**Pull request merged**
